title: Go (for it) Birds!
plugins:
  - jekyll-feed
baseurl: "/GoForItBirds"
incremental: true
exclude:
  - venv/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - README.md
  - generate_pages.py
  - generate_pages_csv_eagles_4th_downs_all_time.R
  - requirements.txt
  - GoForItBirds.code-workspace
  - build_site.sh
  - bin/
  - .vscode/
  - .jekyll-cache/