name: generate_pages_game_season

permissions:
  contents: write

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Run Python script
        run: python scripts/generate_pages_game_season.py

      - name: Commit and push CSV updates
        uses: EndBug/add-and-commit@v9
        with:
          message: "Automated CSV update"
          add: "index.md seasons/*.md games/*.md"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}