name: generate-csv-eagles-all-plays

permissions:
  contents: write

on:
  schedule:
    - cron: '0 5 * * *' # At 01:00 AM Eastern Time
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    container: ghcr.io/bjmapes/goforitbirds/r:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run R script
        run: Rscript scripts/generate_csv_eagles_all_plays.R TRUE

      - name: Commit updates if changed
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config user.email "actions@users.noreply.github.com"
          git config user.name "github-actions"
          git add _data/games_index.json assets/data/games_index.json assets/data/pbp/**
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git pull --ff-only
            git commit -m "chore: update all plays"
            git push
          fi