name: Update 4th Down Data

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2


      - name: Setup R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: nflfastR

      - name: Run R script
        run: Rscript generate_csv_eagles_4th_downs_all_time.R

      - name: Commit and push CSV updates
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add _data/*.csv assets/data/*.csv
          git commit -m 'Automated CSV update' || echo "No changes to commit"
          git push